"""add sync state

Revision ID: 380cf894287f
Revises: 5240cdd2c8aa
Create Date: 2014-06-14 01:43:19.998031

"""

# revision identifiers, used by Alembic.
revision = '380cf894287f'
down_revision = '5240cdd2c8aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syncstate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('last_sync_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_unique_constraint(None, 'user', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user')
    op.drop_table('syncstate')
    ### end Alembic commands ###
