"""add name to app

Revision ID: 39e7350b9749
Revises: 54674a069cd6
Create Date: 2014-06-14 14:15:29.440311

"""

# revision identifiers, used by Alembic.
revision = '39e7350b9749'
down_revision = '54674a069cd6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cwearapplication', sa.Column('name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cwearapplication', 'name')
    ### end Alembic commands ###
