"""add name cwear app

Revision ID: 481b3136349a
Revises: 54c0a40c0167
Create Date: 2014-06-14 16:05:27.884399

"""

# revision identifiers, used by Alembic.
revision = '481b3136349a'
down_revision = '54c0a40c0167'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cwearapplication', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cwearapplication')
    ### end Alembic commands ###
