"""create cwear account

Revision ID: 54674a069cd6
Revises: 380cf894287f
Create Date: 2014-06-14 13:54:36.066250

"""

# revision identifiers, used by Alembic.
revision = '54674a069cd6'
down_revision = '380cf894287f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dcaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hapiaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_key', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cwearapplication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.Column('dcaccount', sa.Integer(), nullable=True),
    sa.Column('hapiaccount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dcaccount'], ['dcaccount.id'], ),
    sa.ForeignKeyConstraint(['hapiaccount'], ['hapiaccount.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cwearapplication')
    op.drop_table('hapiaccount')
    op.drop_table('dcaccount')
    ### end Alembic commands ###
