"""cwear app updates

Revision ID: 54c0a40c0167
Revises: 3536c6c8aec
Create Date: 2014-06-14 15:53:30.002035

"""

# revision identifiers, used by Alembic.
revision = '54c0a40c0167'
down_revision = '3536c6c8aec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cwearapplication', sa.Column('last_sync_time', sa.DateTime(), nullable=True))
    op.add_column('cwearapplication', sa.Column('sync_freq_secs', sa.Integer(), nullable=True))
    op.add_column('syncstate', sa.Column('hapiaccount_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('syncstate', 'hapiaccount_id')
    op.drop_column('cwearapplication', 'sync_freq_secs')
    op.drop_column('cwearapplication', 'last_sync_time')
    ### end Alembic commands ###
